### Build separate functionalities of blackbox

In [94]:
import pandas as pd
import numpy as np
import itertools


from sklearn.linear_model import LinearRegression , LogisticRegression, Lasso, Ridge
from sklearn.datasets import load_iris

## Logistic regression

In [ ]:
X, y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0, solver='lbfgs',
                         multi_class='multinomial').fit(X, y)

In [39]:
clf.predict(X[:1])

array([0])

In [12]:
pred = clf.predict(X[:, :])

pred_proba = clf.predict_proba(X[:, :]) 

clf.score(X, y)

0.97333333333333338

In [13]:
X.shape, y.shape

((150, 4), (150,))

In [20]:
clf.classes_, clf.intercept_, clf.coef_

(array([0, 1, 2]),
 array([  9.88122046,   2.21933911, -12.10055958]),
 array([[-0.42339404,  0.96169816, -2.5194863 , -1.08599106],
        [ 0.53412598, -0.31795306, -0.20537464, -0.93963409],
        [-0.11073193, -0.6437451 ,  2.72486094,  2.02562516]]))

In [64]:
n_classed, n_features = clf.coef_.shape
n_intercept = clf.fit_intercept*1

In [65]:
M = np.concatenate([
    np.eye(n_features),
    np.zeros((n_intercept,n_features))
               ])

In [66]:
clf.decision_function(M)

array([[  9.45782642,   2.75346509, -12.21129151],
       [ 10.84291862,   1.90138605, -12.74430467],
       [  7.36173416,   2.01396448,  -9.37569864],
       [  8.7952294 ,   1.27970502, -10.07493442],
       [  9.88122046,   2.21933911, -12.10055958]])

In [60]:
clf.predict_proba(M)

array([[  9.98775945e-01,   1.22405504e-03,   3.87873159e-10],
       [  9.99869177e-01,   1.30823248e-04,   5.70351069e-11],
       [  9.95263732e-01,   4.73621395e-03,   5.35751592e-08],
       [  9.99455726e-01,   5.44267989e-04,   6.37610616e-09],
       [  9.99529799e-01,   4.70200358e-04,   2.83942218e-10]])

In [61]:
clf.predict(M)

array([0, 0, 0, 0, 0])

In [62]:
clf.fit_intercept

True

In [96]:
M

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [148]:
def unbox(model, modeltype='linear', method = 'whitebox', scope = 'minimal' , samples = 1000):
    n_classed, n_features = clf.coef_.shape
    n_intercept = clf.fit_intercept*1
    
    if scope == 'minimal':
        M = np.concatenate([
                np.eye(n_features),
                -np.eye(n_features),
                np.zeros((n_intercept,n_features))
                       ])
        
        
    elif scope =='maximal':
        M = np.array(list(itertools.product([0, 1], repeat=n_features)))
        M = np.concatenate([M,-M])
        
    elif scope =='bootstrap':
        M = np.array(list(itertools.product([0, 1], repeat=n_features)))
        M = np.concatenate([M]*samples)
        
    pred_linear = model.decision_function(M)
    pred_proba = model.predict_proba(M)
    
    
    return M,P
    
    
    

5

In [135]:
samp = np.random.rand(M.shape[0])

In [149]:
M

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [150]:
pred_proba = clf.predict_proba(-M)

In [146]:
np.cumsum(pred_proba,axis=0)

array([[  9.98775945e-01,   1.22405504e-03,   3.87873159e-10],
       [  1.99864512e+00,   1.35487828e-03,   4.44908266e-10],
       [  2.99390885e+00,   6.09109224e-03,   5.40200674e-08],
       [  3.99336458e+00,   6.63536023e-03,   6.03961736e-08],
       [  4.99289438e+00,   7.10556058e-03,   6.06801158e-08]])

In [139]:
samp

array([ 0.5541441 ,  0.63393745,  0.06164255,  0.08332779,  0.3358227 ])

In [128]:
np.concatenate([M]*10)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  

In [115]:
pred_proba.reshape((1,))

ValueError: cannot reshape array of size 450 into shape (1,)

In [109]:
unbox(clf)

In [99]:
P = clf.predict_proba(M)

In [120]:
M

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [119]:


P*1000

array([[  9.98775945e-01,   1.22405504e-03,   3.87873159e-10],
       [  9.99869177e-01,   1.30823248e-04,   5.70351069e-11],
       [  9.95263732e-01,   4.73621395e-03,   5.35751592e-08],
       [  9.99455726e-01,   5.44267989e-04,   6.37610616e-09],
       [  9.99529799e-01,   4.70200358e-04,   2.83942218e-10]])

In [90]:
lst = np.array(list(itertools.product([0, 1], repeat=3)))

In [91]:
type(M)

numpy.ndarray

In [93]:
np.array(lst)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [ ]:
    if scope == 'minimal':
        M = np.concatenate([
                np.eye(n_features),
                np.zeros((n_intercept,n_features))
                       ])